[package]
name = "group_to_LOE"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = { version = "0.27.0", default-features = false }
geojson = "0.24.1"
serde = "1.0.152"
serde_json = "1.0"
anyhow = "1.0.79"
fs-err = "2.11.0"